# Generated by Django 3.0.8 on 2020-08-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familycards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='comments',
            new_name='notes',
        ),
    ]
